### ISSUE TITLE
About the training iterations on Cityscapes

### ISSUE THREAD

**Issue by hsfzxjy** [ycszen/TorchSeg#100]
I notice that you train all models for 80 epochs on Cityscapes, but using `niters_per_epoch=1000`. So the total iterations is actually 80000, right?

**Comment by JosephChenHub** [comment]
In my opinion, the training set consists of 2,795 images and the train_scale_array is set to [0.75, 1.0, 1.25, 1.5, 1.75, 2.0], so the exact number of sampling of one epoch should be 2795*6 ~= 1000*16.
