### ISSUE TITLE
A exception occurred during Engine initialization, give up running process

### ISSUE THREAD

**Issue by pawopawo** [ycszen/TorchSeg#105]
`python3 -m torch.distributed.launch --nproc_per_node=8 train.py`
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
05 20:17:29 PyTorch Version 1.0.0, Furnace Version 0.1.1
2
05 20:17:31 WRN A exception occurred during Engine initialization, give up running process

hope for help

**Comment by tjucwb** [comment]
do you know what happens here, I also come across this problem, and am wondering if u have solutions to it, thanks @pawopawo
