### ISSUE TITLE
Attention Refinement Module is slightly different from the on in paper

### ISSUE THREAD

**Issue by hubutui** [ycszen/TorchSeg#28]
According to your paper, feature is first global avarage pooling, 1x1 conv, bn, sigmoid to create a weighted vector, and multiply this weighted vector to input feature to get the final output.  However, according to the definition in:
https://github.com/ycszen/TorchSeg/blob/master/furnace/seg_opr/seg_oprs.py#L155-L175
An extra conv-bn-relu block is prepend in the ARM, which is not mentioned in the paper. Do I understand it right?

**Comment by ycszen** [comment]
Yes. This extra conv-bn-relu block is used for uniforming the channels of each stage.  In this repo, we put this conv-bn-relu in the Attention Refinement Module.
