### ISSUE TITLE
how to download the trained model?

### ISSUE THREAD

**Issue by luodahei** [ycszen/TorchSeg#3]
The link of BaiduDrive and GooleDrive is efficacy

**Comment by AIHEKUKAFEIDEXIAOAFEI** [comment]
> The link of BaiduDrive and GooleDrive is efficacy

but now the link of BaiduDrive and GooleDrive is inefficacy,can you help me and give me a efficacy link?

**Comment by ycszen** [comment]
I have released the trained models.
