### ISSUE TITLE
Image normalization during evaluation mode

### ISSUE THREAD

**Issue by ms-krajesh** [ycszen/TorchSeg#33]
I wants to use image normalization during evaluation mode. For this, I have subtracted channel-wise mean from the  original image. Then feed the image to the model. I am not getting expected mean IoU outcome. I think model is not aware from the mean subtraction. Does anyone knows where I am doing mistake?

**Comment by ycszen** [comment]
The normalization method in the evaluation phase should be the same as the training phase.
If you subtract channel-wise mean value in evaluation, the input should only be subtracted the mean value when training.
