### ISSUE TITLE
About CamVid dataset

### ISSUE THREAD

**Issue by 980380446** [ycszen/TorchSeg#49]
I have downloaded the CamVid dataset, but the labels are RGB format and 32 classes, I want to convert the labels to 11 classes and index, how can i do it?

**Comment by ycszen** [comment]
Maybe you can use the dataset in this repo: https://github.com/alexgkendall/SegNet-Tutorial/tree/master/CamVid

**Comment by chenwydj** [comment]
> Maybe you can use the dataset in this repo: https://github.com/alexgkendall/SegNet-Tutorial/tree/master/CamVid

But the images and annotations in that repo are of size 360x480, different from the origin size (720x960). How did you deal with this issue?

Thank you!
