### ISSUE TITLE
where is the train.py and eval.py

### ISSUE THREAD

**Issue by blueardour** [ycszen/TorchSeg#5]
Hi, @ycszen 

Thanks for sharing the excellent project. However, i didn't find some related script files as described in the readme.  Are they still in progress?

**Comment by ycszen** [comment]
Thanks for your appreciate. The `train.py` and `eval.py` are located in each folder of experiment, for example, this [path](https://github.com/ycszen/TorchSeg/tree/master/model/dfn/cityscapes.dfn.R101_v1c).

**Comment by blueardour** [comment]
Very thanks for the tips.
