### ISSUE TITLE
where do you transform the labels for Cityscape dataset

### ISSUE THREAD

**Issue by yaoqi-zd** [ycszen/TorchSeg#50]
Hi, the original cityscape dataset has 33 classes while usually we only use 19 classes. so may I ask you where do you transform the original labels to the ones we use for training ?

I see in cityscapes.py file, you have defined a function named transform_label. However, I didn't find any usage of this function.

**Comment by ycszen** [comment]
When training, we use the transformed dataset, which may be faster and clearer than we transform the label online.
And we utilize the ''transform_label'' function to upload the correct prediction to the official testing server.
