### ISSUE TITLE
 module 'torch.distributed' has no attribute 'ReduceOp'

### ISSUE THREAD

**Issue by zpmmehrdad** [ycszen/TorchSeg#53]
Hi everyone,

I installed all requirements and when I run python eval.py I got this error:
module 'torch.distributed' has no attribute 'ReduceOp'
my Torch version is 1.1.0
thanks.

**Comment by ycszen** [comment]
Could you give more details? 
Meanwhile, in the eval.py script, it didn't call the 'torch.distributed' or 'ReduceOp'.
Therefore, I need more details to know why you get this problem.

**Comment by jay1009** [comment]
I met this problem, too.
But it occurred when I run python train.py.
Can you tell me what happened about it?
![ReduceOp](https://user-images.githubusercontent.com/28528806/61764267-29c28d00-ae0b-11e9-82e1-470f7d5acbe6.jpg)

**Comment by jay1009** [comment]
I met this problem, too.
But it occurred when I run python train.py.
Can you tell me what happened about it?
thanks.
![ReduceOp](https://user-images.githubusercontent.com/28528806/61792129-9448ec80-ae4e-11e9-84fa-4d362be38b32.jpg)

**Comment by ycszen** [comment]
@jay1009 
You need to use this script to run train.py as follows:
```
export NGPUS=8
python -m torch.distributed.launch --nproc_per_node=$NGPUS train.py
```

**Comment by jay1009** [comment]
@ycszen
Thanks for your reply. But I only have one GPU, and after I use
export NGPUS=1
python -m torch.distributed.launch --nproc_per_node=$NGPUS train.py
It still met the same problem.
Is it necessary to use 8 gpus to run this program?

![ReduceOp](https://user-images.githubusercontent.com/28528806/62548429-5b226a80-b899-11e9-9b00-cb82947fe388.jpg)
