### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/bixin/a_project/TorchSeg/log/cityscapes.bisenet.R18.speed/val_2019_06_18_21_54_58.log'

### ISSUE THREAD

**Issue by EchoAmor** [ycszen/TorchSeg#54]
i just want to test this code,when I run eval.py，How to solve this problem please? I have created a directory /log ,but it's still caan't work.Can someone help me please?

**Comment by EchoAmor** [comment]
`/home/bixin/anaconda3/envs/BiSenet/bin/python /home/bixin/a_project/TorchSeg/model/bisenet/cityscapes.bisenet.R18.speed/eval.py
18 21:54:58 using devices 0
Traceback (most recent call last):
  File "/home/bixin/a_project/TorchSeg/model/bisenet/cityscapes.bisenet.R18.speed/eval.py", line 125, in <module>
    config.link_val_log_file)
  File "/home/bixin/a_project/TorchSeg/furnace/engine/evaluator.py", line 81, in run
    results = open(log_file, 'a')
FileNotFoundError: [Errno 2] No such file or directory: '/home/bixin/a_project/TorchSeg/log/cityscapes.bisenet.R18.speed/val_2019_06_18_21_54_58.log'`

**Comment by Jingchensun** [comment]
i meet the problem, too.

**Comment by ycszen** [comment]
Maybe you can create the file with the same path of the error.
I will modify the code to fix this problem.
