### ISSUE TITLE
The detaile infromation of environment config

### ISSUE THREAD

**Issue by Jingchensun** [ycszen/TorchSeg#56]
Thanks for your work!
Could you provide your detail information for environment config, such as the version of CUDA, the version of cudnn, the version of pytorch(is pytorch 1.0.0 or pytorch 1.0.1 ?),the version of python, linux and so on. Which can help me save  lots of time, I tried many times fail to run the code just because of different environment config.

**Comment by ycszen** [comment]
Thanks for your attention.
Our environment config is as follows:
PyTorch 1.0
Python 3.5
CUDA 9.0
Linux Ubuntu 16.04.06 LTS
