### ISSUE TITLE
very low miou using your uploaded model params

### ISSUE THREAD

**Issue by mengzhibin** [ycszen/TorchSeg#57]
i down load https://drive.google.com/file/d/1hFF-J9qoXlbVRRUr29aWeQpL4Lwn45mU/view, then put it in the corresponding folder and rename it epoch-last.pth. eval result is very bad as below:
`08 11:40:17 using devices 0
08 11:40:17 Load Model: /home/mengzhibin/learn/TorchSeg/log/cityscapes.bisenet.R18/snapshot/epoch-last.pth
08 11:40:20 Load model, Time usage:
        IO: 2.575568914413452, initialize parameters: 0.02306199073791504
08 11:40:20 GPU 0 handle 500 data.
  0%|                                                                                                                                                      | 0/500 [00:00<?, ?it/s]08 11:40:20 Load Model on Device 0: 0.00s
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [05:37<00:00,  1.47it/s]
1 road          0.000%
2 sidewalk      1.077%
3 building      1.571%
4 wall          0.472%
5 fence         2.899%
6 pole          0.482%
7 traffic light 0.000%
8 traffic sign  0.007%
9 vegetation    0.244%
10 terrain      0.913%
11 sky          0.000%
12 person       0.175%
13 rider        0.050%
14 car          0.279%
15 truck        0.000%
16 bus          0.060%
17 train        0.000%
18 motorcycle   0.052%
19 bicycle      0.142%
----------------------------     mean_IU        0.443%  mean_IU_no_back 0.468%  mean_pixel_ACC  0.855%
08 11:45:58 Evaluation Elapsed Time: 337.67s
`
is there something wrong?

**Comment by ycszen** [comment]
Are there more details? Are you sure you load the right checkpoint?

**Comment by ArgentLo** [comment]
@mengzhibin 
Probably because you are using `***_labelIds.png` as GT imgs. 
While the model was trained using `TrainId`.

(ref: https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py)

**Comment by mengzhibin** [comment]
@ArgentLo Thanks Very much, I will have a try.
