### ISSUE TITLE
Why do not use the predict value of Border network to help the segment result in DFN when in evaluation step?

### ISSUE THREAD

**Issue by pdoublerainbow** [ycszen/TorchSeg#58]
Hi, thanks for your open source. I have a question about why in the evalution step, you do not use the predict of Border network to help the segment result in DFN. I still have a question about if i want to use the predict of Border network to help the segment result, what should i do ? I can't figure out a prefect Strategy about this. I am looking forward to your reply, Thanks.

**Comment by ycszen** [comment]
In my future work, I am also attempting to utilize the prediction of Border Network to help the segmentation prediction.

**Comment by pdoublerainbow** [comment]
@ycszen Looking forward to your future work.

**Comment by ycszen** [comment]
Thanks. We can discuss it further~
