### ISSUE TITLE
How to train on a single gpu?

### ISSUE THREAD

**Issue by DRosemei** [ycszen/TorchSeg#63]
I have modified train.py as #11 said, but I find that there is no code   `model = DataParallelModel(model, device_ids=engine.devices)`
and error occoured:
`Traceback (most recent call last):
  File "train.py", line 33, in <module>
    with Engine(custom_parser=parser) as engine:
  File "/home/rose/projects/TorchSeg/furnace/engine/engine.py", line 69, in __init__
    self.devices = parse_devices(self.args.devices)
  File "/home/rose/projects/TorchSeg/furnace/utils/pyt_utils.py", line 99, in parse_devices
    device = int(d)
ValueError: invalid literal for int() with base 10: ''
`
Then I used the unrevised 'train.py' and changed NGPUS=1. It made the same error. Could someone can tell me why?

**Comment by bkunsberg** [comment]
@DRosemei 

I have the same error -- can you tell me what you did to fix this (as you closed it)?  Much appreciated!

**Comment by buzhiqimeiliuqiangdong** [comment]
> I have modified train.py as #11 said, but I find that there is no code `model = DataParallelModel(model, device_ids=engine.devices)`
> and error occoured:
> `Traceback (most recent call last): File "train.py", line 33, in <module> with Engine(custom_parser=parser) as engine: File "/home/rose/projects/TorchSeg/furnace/engine/engine.py", line 69, in __init__ self.devices = parse_devices(self.args.devices) File "/home/rose/projects/TorchSeg/furnace/utils/pyt_utils.py", line 99, in parse_devices device = int(d) ValueError: invalid literal for int() with base 10: '' `
> Then I used the unrevised 'train.py' and changed NGPUS=1. It made the same error. Could someone can tell me why?

**Comment by buzhiqimeiliuqiangdong** [comment]
> I have modified train.py as #11 said, but I find that there is no code `model = DataParallelModel(model, device_ids=engine.devices)`
> and error occoured:
> `Traceback (most recent call last): File "train.py", line 33, in <module> with Engine(custom_parser=parser) as engine: File "/home/rose/projects/TorchSeg/furnace/engine/engine.py", line 69, in __init__ self.devices = parse_devices(self.args.devices) File "/home/rose/projects/TorchSeg/furnace/utils/pyt_utils.py", line 99, in parse_devices device = int(d) ValueError: invalid literal for int() with base 10: '' `
> Then I used the unrevised 'train.py' and changed NGPUS=1. It made the same error. Could someone can tell me why?

handsome man，do you solve your problem? I have the same error.嘤嘤嘤

**Comment by buzhiqimeiliuqiangdong** [comment]
@DRosemei @bkunsberg handsome guys，do you solve your problem? I have the same error.嘤嘤嘤

**Comment by Antidoht** [comment]
try to put key --devices=0

**Comment by claus25** [comment]
hello please I have the same problem 
please where to put key --devices=0?
