### ISSUE TITLE
Question about read voc dataset

### ISSUE THREAD

**Issue by WeihongM** [ycszen/TorchSeg#65]

**Comment by WeihongM** [comment]
Hello, thanks for your open-source code!
I have one question about your  voc dataset loading.
In file datasets/Basedataset.py, you directly read the gt mask value from function cv2.grayscale, however, dont you need to **remap the pixel valu**e to the class index(such as 0~class_num).

**Comment by WeihongM** [comment]
More concretely, I mean why no use Image p mode to read the mask image, because if we use cv2.grayscale, how can we know the mapping value from the RGB image.

**Comment by ycszen** [comment]
Of course, you can use the Image P mode to read the ground truth. 
In our experiments, we use the cv2.grayscale to read the ground truth, which also gives us a binary mask, not a RGB image.

**Comment by WeihongM** [comment]
Thanks for your reply.
Do you preprocess the voc image. I could not get image value range from (0~num classes) using cv2.grayscale from my download voc dataset.   Maybe it needs to preprocess the dataset, such as mapping to range(0~num classes)? Or my dataset goes wrong...

**Comment by jay1009** [comment]
@WeihongM hi, I also met this problem, and my dataset is download from official website. If you find any solution, please tell me
Thank you.

**Comment by WeihongM** [comment]
@jay1009  I dont use cv2 to read data, directly use PIL.

**Comment by jay1009** [comment]
@WeihongM Thanks for your reply.
After you use PIL, did you make your own label for gt?

**Comment by jay1009** [comment]
@WeihongM Thank you. I will try it as you say.
