### ISSUE TITLE
A Problem about Image Preprocessing

### ISSUE THREAD

**Issue by myknowntime** [ycszen/TorchSeg#66]
Thank you for your masterpiece, I think your codes are very helpful. But I have a question about image preprocessing in "model\dfn\cityscapes.dfn.R101_v1c\dataloader" Trainpre : 
id255 = np.where(gt == 255)
no255_gt = np.array(gt)
no255_gt[id255] = 0
why transform gts (equal to 255) to 0? I can't understand . Maybe this question is simple but your reply will help me a lot！  
I thik this is to process the inputs of Border Network to optimize border information, but I still why need to transform 255 to 0 in gt?

**Comment by ycszen** [comment]
In PASCAL VOC dataset, the ignore_labels (255) mainly exist on the boundary of objects. If we didn't transform the 255 to 0, there would be two boundaries of one objects after Canny operation. Therefore, we transform the 255 to 0.
