### ISSUE TITLE
Xception39 pretrained model

### ISSUE THREAD

**Issue by lxtGH** [ycszen/TorchSeg#67]
Hi!!!! Thanks for sharing your code. I wonder if you plan to release Xception39 pretrained model ??

**Comment by ycszen** [comment]
Actually, this plan has a low priority because I have no machines to pre-train the Xception39 on ImageNet with PyTorch.

**Comment by lxtGH** [comment]
Can you share the training details and results on ImageNet val ? I am interested in that model. Maybe I can train and release the weight in this repo.

**Comment by ycszen** [comment]
I’m sorry that the Xception pre-trained model is trained by someone else. Now I can not find its log. Maybe you can check the training details of the original paper of Xception. We just adapt its structure.
