### ISSUE TITLE
focal loss疑惑

### ISSUE THREAD

**Issue by GuangyanZhang** [ycszen/TorchSeg#68]
您好，看你的focalloss 和论文给的不一样，请问您是经过试验自己修改的吗？还有用的focalloss显示的是维度不匹配，请问您是在算法focal loss的时候对label要先做onehot处理吗？我仔细看了下您的代码，好像没有看到这步操作，开源帮我解答下吗？

**Comment by ycszen** [comment]
I will update the implementation of focal-loss in the mmdetection.
