### ISSUE TITLE
too many bugs

### ISSUE THREAD

**Issue by mengzhibin** [ycszen/TorchSeg#69]
In the beggining, Thanks for your work. But have you tested your code? for example 
`colors = self.dataset.get_class_colors` is type of method which is wrong code. many other bugs are also found, do your paper result get result from this code?

**Comment by ycszen** [comment]
Hi,
I am sorry there are some bugs. I will try my best to fix them.

Our original experiments are implemented on our own framework. This repo is a re-implementation on PyTorch. 

The `colors = self.dataset.get_class_colors` is used in the visualization part, which indeed has not been  tested. However, the codes about performance and experiments have been tested and can be reproduced.
