### ISSUE TITLE
software dependence error

### ISSUE THREAD

**Issue by blueardour** [ycszen/TorchSeg#7]
hi, @ycszen 

Sorry to disturb you. This project is so attractive that I want to re-produce the result with it. However, when I tried to run train.py in TorchSeg/model/dfn/voc.dfn.R101_v1c. It gave several warnings and errors. They were the software dependence issues.  This I wonder if you could share your software version in your environment. 

My is:  centos7.5 + python3.6.8 + pytorch1.0 + cuda9.0 + gcc-4.9.4.

Error message:

`
/home/cat/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/cpp_extension.py:166: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  platform=sys.platform))
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    from apex.parallel import DistributedDataParallel, SyncBatchNorm
ModuleNotFoundError: No module named 'apex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 27, in <module>
    "Please install apex from https://www.github.com/nvidia/apex .")
ImportError: Please install apex from https://www.github.com/nvidia/apex .

`

When I tried to install apex by `pip install apex`, it gave 
`In file included from /home/chenp/.pyenv/versions/3.6.8/include/python3.6m/Python.h:39:0,
                     from cryptacular/bcrypt/_bcrypt.c:26:
    crypt_blowfish-1.2/crypt.h:17:23: fatal error: gnu-crypt.h: No such file or directory
     #include <gnu-crypt.h>
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1`

**Comment by ycszen** [comment]
Hi, my software environments are as follows:
```
Ubuntu 16.04
PyTorch 1.0
Python 3.5.2
Cuda 9.0
GCC 5.4.0
```
According to my experimence, the warning you showed is normal. Then you should install the `apex` to use the multi-process-sync-bn.

**Comment by daodaofr** [comment]
hi, @ycszen.
I got a similar issue, when I run "python train.py -d 0-2", it gives a segmentation fault.
Do you have any idea ?

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
/home/daodao/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py:166: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
13 10:32:26 PyTorch Version 1.0.0, Furnace Version 0.1.1
13 10:32:26 using devices 0, 1, 2
[00:00<?,?it/s]Segmentation fault (core dumped)

**Comment by blueardour** [comment]
thanks very much @ycszen 
I have successfully run the script.

**Comment by Mr-doooog** [comment]
@daodaofr Did you solve this question? I meet the same one

**Comment by daodaofr** [comment]
@Mr-doooog I was using the wrong labels (*_color.png), you need to use *_labelledIds.png.
