### ISSUE TITLE
What's the difference about pretrained model?

### ISSUE THREAD

**Issue by sfdn123** [ycszen/TorchSeg#73]
Hi, thanks for your great work.
I want to know the difference between resnet18_v1.pth, cityscapes-bisenet-R18.pth and cityscapes-bisenet-R18-speed.pth.

I thought as follows
・'resnet18_v1.pth' is pretrained ResNet18_model by ImageNet
・'cityscapes-bisenet-R18.pth' is all_trained model by cityscapes dataset(non_speed_model) and resnet18 part was finetuned
・'cityscapes-bisenet-R18-speed.pth' is all_trained model by cityscapes dataset(speed_model) and resnet18 part was finetuned

Are these correct?

**Comment by ycszen** [comment]
Yes. Your understanding is correct.

**Comment by sfdn123** [comment]
thanks for your reply
