### ISSUE TITLE
你的网络运行时间太久了

### ISSUE THREAD

**Issue by 1261017506** [ycszen/TorchSeg#79]

**Comment by 1261017506** [comment]
作者好，我运行了你的psp网络，发现一张卡训练一个epoch也需要跑一晚上，实在是太慢了

**Comment by ycszen** [comment]
我们一般需要用4张卡或者8张卡训练。ResNet50作为backbone，训练80个epoch，大概一天的时间。

**Comment by ycszen** [comment]
训练用的GPU是1080Ti
