### ISSUE TITLE
There is a error in model/bisenet/cityscapes.bisenet.R18/train.py

### ISSUE THREAD

**Issue by FengZhiTeng** [ycszen/TorchSeg#84]
for i in range(2):
    optimizer.param_groups[0]['lr'] = lr
for i in range(2, len(optimizer.param_groups)):
    optimizer.param_groups[i]['lr'] = lr * 10
I think that the second line has a error, the 0 is supposed to be inplaced by i

**Comment by ycszen** [comment]
Yes. You are right.
I have fixed it.
