### ISSUE TITLE
There is a error in model/bisenet/cityscapes.bisenet.R18.speed/eval.py

### ISSUE THREAD

**Issue by FengZhiTeng** [ycszen/TorchSeg#86]
pred = self.whole_eval(img,
                               (config.image_height // config.gt_down_sampling,
                                config.image_width // config.gt_down_sampling),
                               device)
I think the fourth line should be device=device

**Comment by ycszen** [comment]
Yes. You are right. Thanks for pointing it out.  
I have fixed them.
