### ISSUE TITLE
On COCO dataset

### ISSUE THREAD

**Issue by shivSD** [ycszen/TorchSeg#92]
Do you have any pretrained weights for COCO dataset. If not do you have any train.py or script to load the COCO dataset. Appreciate any help.

**Comment by shivSD** [comment]
Sorry got it under dataset/coco

**Comment by shivSD** [comment]
looks like the coco dataset folder is incomplete

**Comment by ycszen** [comment]
Thanks for pointing it out.
The datasets of COCO is incomplete. I have removed it.
