### ISSUE TITLE
I have a question about the BN layer. 

### ISSUE THREAD

**Issue by huang229** [ycszen/TorchSeg#95]
This is a great job, thank you for your open source sharing.
Excuse me, why do you write the BN layer script alone? Isn't there a defined BN in Pytorch? Is there something wrong with the BN layer of  Pytorch? I use the BN layer of pytorch. When the size of batch_size is too small, the model test is very bad. I have never encountered this problem in other deep learning frameworks.

**Comment by ycszen** [comment]
This is because the segmentation models require synchronization batch-norm layer. 
Therefore, we set an interface for bn layer in order to change it flexibly. 
When the batch_size is small, the model can't compute the accurate mean and std value of batch-norm, which hinders the performance.

**Comment by huang229** [comment]
okay, thank you.
